//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.THUCHANH5.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGiangVien
    {
        public TBLGiangVien()
        {
            this.TBLHuongDans = new HashSet<TBLHuongDan>();
        }
    
        public int Magv { get; set; }
        public string Hotengv { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string Makhoa { get; set; }
    
        public virtual TBLKhoa TBLKhoa { get; set; }
        public virtual ICollection<TBLHuongDan> TBLHuongDans { get; set; }
    }
}
