//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.THUCHANH5.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKhoa
    {
        public TBLKhoa()
        {
            this.TBLGiangViens = new HashSet<TBLGiangVien>();
            this.TBLSinhViens = new HashSet<TBLSinhVien>();
        }
    
        public string Makhoa { get; set; }
        public string Tenkhoa { get; set; }
        public string Dienthoai { get; set; }
    
        public virtual ICollection<TBLGiangVien> TBLGiangViens { get; set; }
        public virtual ICollection<TBLSinhVien> TBLSinhViens { get; set; }
    }
}
