//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.THUCHANH5.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThucTapEntities : DbContext
    {
        public ThucTapEntities()
            : base("name=ThucTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBLDeTai> TBLDeTais { get; set; }
        public DbSet<TBLGiangVien> TBLGiangViens { get; set; }
        public DbSet<TBLHuongDan> TBLHuongDans { get; set; }
        public DbSet<TBLKhoa> TBLKhoas { get; set; }
        public DbSet<TBLSinhVien> TBLSinhViens { get; set; }
    }
}
